version: '3.6'
services:
  postgres:
    container_name: "postgres"
    pid: "postgres"
    image: postgres:latest
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: Ro-main17
      POSTGRES_DB: sandbox_db
  # django
  backend:
    container_name: "backend"
    pid: "backend"
    environment:
      - TZ=Etc/UTC
    expose:
      - "8000"
    working_dir: /home/car_sharing/backend
    depends_on:
      - postgres
      - front-end
  # vuejs / node
  front-end:
    container_name: "front-end"
    pid: "front-end"
    environment:
      - TZ=Etc/UTC
    expose:
      - "8001"
    working_dir: /home/car_sharing/front-end
 
