version: '3.7'
services:
  postgres:
    volumes:
      - postgres_volume:/var/lib/postgresql/data
  # django
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - SQL_HOST=postgres
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/home/sandbox/backend/
    depends_on:
      - postgres
      - front-end
  # vuejs
  front-end:
    build: ./front-end
    ports:
      - "8001:8001"
    environment:
      - BACKEND_SERVICE=backend
      - BACKEND_SERVICE_PORT=8000
    command: npm run serve 
    volumes:
      - ./front-end:/home/sandbox/front-end/
volumes:
  postgres_volume:
