# Generated by Django 2.2 on 2019-08-07 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarMaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Car maker', max_length=100, verbose_name='Name')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated on')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(help_text="Car's model", max_length=100, verbose_name='Model')),
                ('year', models.PositiveIntegerField(help_text="Car's year", verbose_name='Year')),
                ('seats', models.PositiveIntegerField(help_text="Car's number of seats", verbose_name='Seats')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated on')),
                ('maker', models.ForeignKey(help_text="Car's maker", on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='car_sharing.CarMaker')),
            ],
        ),
    ]
